---

- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: "Installiere Softwarepakete"
      package:
        state: present      
        name:      
          - htop
          - vim
          - curl
          - wget
          - sudo
          - neofetch

    - name: "Kopiere .bash_aliases"
      copy:
        src: files/bash_aliases
        dest: /home/wolfgang/.bash_aliases
        user: wolfgang
        group: wolfgang
        mode: u=rw,g=r,o=r



...

